name: Build, Push & Deploy to Azure

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to Azure Container Registry (ACR)
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build the Docker image
      - name: Build the Docker image
        run: |
          docker buildx build --platform linux/amd64 -t ${{ secrets.ACR_LOGIN_SERVER }}/my-app:${{ github.sha }} --push .

      # # Deploy to Azure Container Instances
      # - name: Deploy to Azure Container Instances
      #   uses: azure/aci-deploy@v1
      #   with:
      #     resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
      #     name: my-container-instance
      #     image: ${{ secrets.ACR_LOGIN_SERVER }}/my-app:${{ github.sha }}
      #     os-type: Linux
      #     cpu: 1
      #     memory: 1.5
